#!/bin/sh

export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`

gconftool-2 --direct --config-source=$GCONF_CONFIG_SOURCE \
            --recursive-unset /schemas/apps/panel

gconftool-2 --direct --config-source=$GCONF_CONFIG_SOURCE \
            --load /usr/etc/gconf/schemas/panel-default-setup.entries

gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/clock.schemas \
    /usr/etc/gconf/schemas/fish.schemas \
    /usr/etc/gconf/schemas/gnome-panel-screenshot.schemas \
    /usr/etc/gconf/schemas/panel-compatibility.schemas \
    /usr/etc/gconf/schemas/panel-general.schemas \
    /usr/etc/gconf/schemas/panel-global.schemas \
    /usr/etc/gconf/schemas/panel-object.schemas \
    /usr/etc/gconf/schemas/panel-toplevel.schemas \
    /usr/etc/gconf/schemas/window-list.schemas \
    /usr/etc/gconf/schemas/workspace-switcher.schemas

/sbin/ldconfig

# End of file
