#!/bin/sh

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/apps_evolution_addressbook-2.0.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/apps_evolution_calendar-2.0.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/apps_evolution_shell-2.0.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/apps_evolution_summary-2.0.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/evolution-mail-2.0.schemas

# End of file
