#!/bin/bash

/usr/bin/xmlcatalog --noout --add "public" \
    "-//OMF//DTD Scrollkeeper OMF Variant V1.0//EN" \
    "/usr/share/xml/scrollkeeper/dtds/scrollkeeper-omf.dtd" \
    /etc/xml/catalog

# End of file
