#!/bin/sh

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/apps_gnome_settings_daemon_default_editor.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/apps_gnome_settings_daemon_keybindings.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/apps_gnome_settings_daemon_screensaver.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/desktop_gnome_font_rendering.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/desktop_gnome_peripherals_keyboard_xkb.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/fontilus.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/themus.schemas

# End of file
