#!/bin/sh

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/desktop_default_applications.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/desktop_gnome_url_handlers.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/system_dns_sd.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/system_http_proxy.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/system_smb.schemas

# End of file
