#!/bin/sh

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/CDDB-Slave2.schemas \
	/usr/etc/gconf/schemas/gnome-audio-profiles.schemas \
    /usr/etc/gconf/schemas/gnome-cd.schemas \
    /usr/etc/gconf/schemas/gnome-sound-recorder.schemas

# End of file
