#!/bin/sh

/usr/bin/fc-cache

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/brlmonitor.schemas \
    /usr/etc/gconf/schemas/gnopernicus.schemas \
    /usr/etc/gconf/schemas/remote.schemas

# End of file
