#!/bin/sh

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/epiphany-lockdown.schemas

GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` \
    gconftool-2 --makefile-install-rule \
    /usr/etc/gconf/schemas/epiphany.schemas

# End of file
